Updates as of 4/20/19

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -1,35 +1,52 @@
 #!/bin/bash
-#Ap Signal Finish Function
-#Description:    Removes temporary files declared
-#---------------------------------------------
-#finish() {
-
-#}Author: Zach Reed
+#Author: Zach Reed
 #Description:  Matrix Script
 #Date: 4/22/2019
 #--------------------------------------------
 
-#Temporary Files in /
-temp_ex=$(mktemp /tmp/test.XXXXXXXX)
-
-rm "$tmpfile"
+#-------------------------------------------
+#Temporary Files Declarations  in /tmp
+row_n=$(mktemp /tmp/row_n.XXXXXXXX)
+col_n=$(mktemp /tmp/col_n.XXXXXXXX)
 
 #-------------------------------------------
-#Function:	Cleanup 
+#Function:      Cleanup
 #Description:    Removes temporary files
 #-------------------------------------------
-cleanup() {
 
-rm "$tmpfile"
-} 
+trap "rm -f $row_n $col_n" INT HUP TERM
+
 
 #--------------------------------------------
 #Dimensions Function
-#Description:	prints out returns from n_row()
-# 		and n_col(), respectively.
-#dims(){
-	
-#}
+#Description:   prints out returns from n_row()
+#               and n_col(), respectively.
+dims(){
+	read  c_line < $1
+	col_n = 0;
+        for i in $c_line
+	do
+		((col_n++))
+	done < "$1"
+	echo "Col:"
+	echo " $col_n"
+}
 
-cleanup
+if [[ $1 == "dims" ]]
+then
+	if [[ $# == "1" ]]
+	then
+		echo "1 argument"
+
+	elif [[ $# == "2" && -r "$2" ]]
+	then
+		echo "--------------"
+        	while read -r line
+       		do
+               		echo "$line"
+ 	       	done < "$1"
+		echo "--------------"
+ 		dims $2
+	fi
+fi
 
